# Generated by Django 5.1.5 on 2025-03-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='ameaca',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='bacia_hidrografica',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome_comum',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='rppn',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='uc_estadual',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='uc_federal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='uso',
            field=models.TextField(),
        ),
    ]
